databases:
  - name: hab_health_booking_system
    databaseName: hab_health_booking_system
    user: hab_health_booking_system

services:
  - type: web
    name: hab_health_booking_system
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hab_health_booking_system
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false